### ISSUE TITLE
 Editar los productos en CustomerOrderHdrItem

### ISSUE THREAD

**Issue by IsraelFonrouge** [tfonrouge/remoteScreen#3]
Editar los productos en CustomerOrderHdrItem

**Comment by tfonrouge** [comment]
* se agrego edicion de campo 'qty'

**Comment by tfonrouge** [comment]
Se editan los campos 'qty' y 'size' , no se edita el valor del producto ni el UPC, porque es preferible eliminar el registro y crear uno nuevo
